export { SPACE_MODULE, spaceFeatureFlags } from "./flags";
export * from "./types";
export {
  ACTOR_ADMIN,
  ACTOR_OBSERVADOR,
  ACTOR_RESIDENTE,
  ACTOR_REVISOR,
  ACTOR_TECNICO,
  DEMO_PLACE_ID,
  DEMO_PIPE_ID,
  createInitialSpaceState,
  demoActors,
  demoObjects,
  demoPlace,
} from "./seed";
export {
  canAssign,
  canAttachEvidence,
  canConfirmDraft,
  canCreateIncident,
  canEditVisit,
  canManageExtensions,
  canTransition,
  roleCanEdit,
  roleCanSetStatus,
} from "./roles";
export { loadSpaceState, resetSpaceDemo, saveSpaceState, spaceDir } from "./store";
export { SAMPLE_CHECKLIST_EXTENSION } from "./extensions";
export {
  acquireObjectLock,
  addVisitComment,
  askAssistant,
  assignIncident,
  attachEvidence,
  confirmDraft,
  correctDecision,
  createDraft,
  createIncident,
  deleteDecision,
  discardDraft,
  getObject,
  getSpaceModuleInfo,
  getSpaceSnapshot,
  installExtension,
  issuePassport,
  listActors,
  listEvidence,
  listIncidents,
  listObjects,
  listPlaces,
  listTimeline,
  recordDecision,
  recordDemoReset,
  releaseObjectLock,
  runMaintenanceDemoFlow,
  transitionIncident,
  uninstallExtension,
  updateDraftObject,
  upsertPresence,
} from "./service";
